defmodule LegatoWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :legato

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_legato_key",
    signing_salt: "KCV2mwCa",
    encryption_salt: "zh5FpzX3",
    same_site: "Lax",
    http_only: true,       # Keeps it secure from JS theft
    max_age: 172_800       # <--- 2 days in seconds
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/sign-in-socket", LegatoWeb.SignInSocket,
    websocket: [connect_info: [session: @session_options]]

  socket "/workspace-socket", LegatoWeb.WorkspaceSocket,
    websocket: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :legato,
    gzip: not code_reloading?,
    only: LegatoWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :legato
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # Read your configuration at compile time
  plug Corsica,
    origins: Application.compile_env(:legato, :cors_origins, []),
    allow_credentials: true,
    allow_headers: :all
  plug LegatoWeb.Router
end
